<a href="https://colab.research.google.com/github/Harshrajgaur13/ML_Lab/blob/main/ML_Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PCA
Linerar Regression
features  s1 s2 s3 s4
x 4 8 13 7
y 11 4 5 14

write a program in python to Principal Component Analysis

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Define the dataset
features = ['s1', 's2', 's3', 's4']
data = np.array([
    [4, 8, 13, 7],   # x
    [11, 4, 5, 14]    # y
])

# Standardize the data
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)

# Compute covariance matrix
cov_matrix = np.cov(data_scaled, rowvar=False)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

# Sort eigenvalues and corresponding eigenvectors
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:, sorted_indices]

# Project data onto principal components
principal_components = np.dot(data_scaled, eigenvectors[:, :2])  # Reduce to 2 components

# Create a DataFrame for the results
pca_df = pd.DataFrame(principal_components, columns=['PC1', 'PC2'])

# Display results
print("Explained Variance:", eigenvalues[:2] / np.sum(eigenvalues))
print("Principal Components:")
print(pca_df)
print(eigenvalues)
print(eigenvectors)


Explained Variance: [1. 0.]
Principal Components:
   PC1  PC2
0  2.0  0.0
1 -2.0  0.0
[ 8.0000000e+00  0.0000000e+00  0.0000000e+00 -8.8817842e-16]
[[-5.00000000e-01 -3.71854204e-18  3.71854204e-18 -8.66025404e-01]
 [ 5.00000000e-01  5.77350269e-01 -5.77350269e-01 -2.88675135e-01]
 [ 5.00000000e-01  2.11324865e-01  7.88675135e-01 -2.88675135e-01]
 [-5.00000000e-01  7.88675135e-01  2.11324865e-01  2.88675135e-01]]


In [ ]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Define the dataset
features = ['s1', 's2', 's3', 's4']
data = np.array([
    [4, 8, 13, 7],   # x
    [11, 4, 5, 14]    # y
])

# Standardize the data
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)

# Apply PCA
pca = PCA(n_components=2)  # Reduce to 2 components
principal_components = pca.fit_transform(data_scaled)

# Create a DataFrame for the results
pca_df = pd.DataFrame(principal_components, columns=['PC1', 'PC2'])

# Display results
print("Explained Variance Ratio:", pca.explained_variance_ratio_)
print("Principal Components:")
print(pca_df)


Explained Variance Ratio: [1.00000000e+00 2.31111593e-33]
Principal Components:
   PC1           PC2
0  2.0 -9.614813e-17
1 -2.0 -9.614813e-17


In [ ]:
x = [4,8,13,7]
y = [11,4,5,14]
x_mean=0
for(i=0;i<5;i++):
  x_mean=x_mean+x[i]

In [ ]:
# Define the dataset
features = ['s1', 's2', 's3', 's4']
data = [
    [4, 8, 13, 7],   # x
    [11, 4, 5, 14]    # y
]

# Compute mean and standard deviation
def mean_std(matrix):
    mean = [sum(col) / len(col) for col in zip(*matrix)]
    std = [(sum((x - m) ** 2 for x in col) / len(col)) ** 0.5 for col, m in zip(zip(*matrix), mean)]
    return mean, std

# Standardize the data
mean, std = mean_std(data)
data_scaled = [[(data[i][j] - mean[j]) / std[j] for j in range(len(data[i]))] for i in range(len(data))]

# Compute covariance matrix
def covariance_matrix(matrix):
    rows, cols = len(matrix), len(matrix[0])
    cov_matrix = [[0] * cols for _ in range(cols)]
    for i in range(cols):
        for j in range(cols):
            cov_matrix[i][j] = sum(matrix[k][i] * matrix[k][j] for k in range(rows)) / (rows - 1)
    return cov_matrix

cov_matrix = covariance_matrix(data_scaled)

# Compute eigenvalues and eigenvectors
def eigendecomposition(matrix):
    from math import sqrt
    def power_iteration(matrix, num_simulations=100):
        b_k = [1] * len(matrix)
        for _ in range(num_simulations):
            b_k1 = [sum(matrix[i][j] * b_k[j] for j in range(len(matrix))) for i in range(len(matrix))]
            norm = sqrt(sum(x**2 for x in b_k1))
            b_k = [x / norm for x in b_k1]
        eigenvalue = sum(b_k[i] * sum(matrix[i][j] * b_k[j] for j in range(len(matrix))) for i in range(len(matrix)))
        return eigenvalue, b_k

    eigenvalue, eigenvector = power_iteration(matrix)
    return [eigenvalue], [eigenvector]


eigenvalues, eigenvectors = eigendecomposition(cov_matrix)

# Project data onto principal components
def project_data(data, eigenvectors):
    return [[sum(data[i][j] * eigenvectors[0][j] for j in range(len(data[i]))) for _ in range(2)] for i in range(len(data))]

principal_components = project_data(data_scaled, eigenvectors)

# Display results
print("Explained Variance:", [eigenvalues[0] / sum(eigenvalues)])
print("Principal Components:")
for row in principal_components:
    print(row)
